# -*- coding: utf-8 -*-
"""Hadoop/mapper3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrGtCebEoozLLsQodLW7xXuMr8HMbXDK
"""

#!/usr/bin/env python3
import sys

# --- Mapper 3: 通用对称拆分与Count传递 ---
# 适用：User-Based 和 Item-Based
# 输入：ID1,ID2 \t Similarity \t Count
# 输出：ID1 \t ID2:Similarity:Count (以及反向)

for line in sys.stdin:
    line = line.strip()
    if not line:
        continue

    try:
        # 解析 Job 2 (reducer2.py) 的输出
        parts = line.split("\t")

        # 安全检查：确保有配对、相似度和计数
        if len(parts) < 3:
            continue

        pair_str = parts[0]
        sim = parts[1]
        count = parts[2] # 保留 Count 用于 Reducer 筛选

        # 拆分 Key "u1,u2" 或 "m1,m2"
        if "," in pair_str:
            id1, id2 = pair_str.split(",")

            # 对称输出：A和B相似，说明A在B的邻居里，B也在A的邻居里

            # 输出给 ID1
            print(f"{id1}\t{id2}:{sim}:{count}")

            # 输出给 ID2
            print(f"{id2}\t{id1}:{sim}:{count}")

    except ValueError:
        continue